### ISSUE TITLE
How does this mod interact with upside-down mobs named Dinnerbone?

### ISSUE THREAD

**Issue by surfrock66** [TomDesch/damageIndicator#11]
We've been looking for a healthbar plugin, but all those we have found end up flipping any mobs named "Dinnerbone" back to upright.  Do you know if this mod handles that properly, will an upside down mob stay upside down but still display health?

**Comment by TomDesch** [comment]
Dear
I've not tested your specific use case but normally if you use the holographic option, then logically it shouldn't affect it because it doesn't alter the name of the mobs directly. 
However, with the non-holographic feature, it would break that.


Please keep me posted whether it works for you. 
If it doesn't, I will make sure to have a fix for that in the near future :) 

Kind regards

**Comment by TomDesch** [comment]
After further investigation I can conclude the holographic healthbar feature does indeed not meddle with special given nametags (although it might hide them with the current implementation)

![image](https://github.com/TomDesch/damageIndicator/assets/29839170/91a7dfdf-29f8-413c-ac05-c09b138b3436)

**Comment by surfrock66** [comment]
Excellent, thank you so much!
